language: node_js
node_js:
- '10'
sudo: false
services: mongodb
before_install: npm install -g greenkeeper-lockfile@1
install: if [[ $TRAVIS_BRANCH == greenkeeper/* ]] && [[ -v TRAVIS_COMMIT_RANGE ]]; then npm install; else npm ci; fi
before_script: greenkeeper-lockfile-update
script:
- npm run lint
- npm run build
after_script: greenkeeper-lockfile-upload
deploy:
  provider: heroku
  api_key:
    secure: QVdHJP0VscOljuW2fgXzEp2Ud1JltdOOnC65QjZ7Zdqc6H0tTxc/omM7Ag6zauUF4kLf4W7Tddmw7fAbOpz+WH4BwRznjJjYDoI4Z2HAtVhQc+qbXJSOhcZG9bSZD0SLAw0zRnJQKXaIocnTawoK9R5KVWt6EDoRISlzaazc5Hw=
  app: kyukou-kyudai
  on:
    all_branches: true
    tags: true
    repo: qdai/kyukou
