language: node_js
node_js:
- '10'
sudo: false
services: mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- npm run lint
after_script: greenkeeper-lockfile-upload
deploy:
  provider: heroku
  api_key:
    secure: QVdHJP0VscOljuW2fgXzEp2Ud1JltdOOnC65QjZ7Zdqc6H0tTxc/omM7Ag6zauUF4kLf4W7Tddmw7fAbOpz+WH4BwRznjJjYDoI4Z2HAtVhQc+qbXJSOhcZG9bSZD0SLAw0zRnJQKXaIocnTawoK9R5KVWt6EDoRISlzaazc5Hw=
  app: kyukou-kyudai
  on:
    all_branches: true
    tags: true
    repo: qdai/kyukou
