language: node_js
node_js:
- '5.0.0'
sudo: false
services: mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- export CXX=g++-4.8
before_script:
- npm install -g gulp
script:
- npm run lint
- gulp ci
deploy:
  provider: heroku
  api_key:
    secure: QVdHJP0VscOljuW2fgXzEp2Ud1JltdOOnC65QjZ7Zdqc6H0tTxc/omM7Ag6zauUF4kLf4W7Tddmw7fAbOpz+WH4BwRznjJjYDoI4Z2HAtVhQc+qbXJSOhcZG9bSZD0SLAw0zRnJQKXaIocnTawoK9R5KVWt6EDoRISlzaazc5Hw=
  app: kyukou-kyudai
  on:
    all_branches: true
    tags: true
    repo: qdai/kyukou
