export const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';
export const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const TOGGLE_ABOUT = 'TOGGLE_ABOUT';
export const TOGGLE_DEPARTMENT = 'TOGGLE_DEPARTMENT';
