const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';
const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST';
const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
const TOGGLE_ABOUT = 'TOGGLE_ABOUT';
const TOGGLE_DEPARTMENT = 'TOGGLE_DEPARTMENT';

export {
  LOAD_EVENTS_FAILURE,
  LOAD_EVENTS_REQUEST,
  LOAD_EVENTS_SUCCESS,
  TOGGLE_ABOUT,
  TOGGLE_DEPARTMENT
};
