const LOAD_LOGS_FAILURE = 'LOAD_LOGS_FAILURE';
const LOAD_LOGS_REQUEST = 'LOAD_LOGS_REQUEST';
const LOAD_LOGS_SUCCESS = 'LOAD_LOGS_SUCCESS';

export {
  LOAD_LOGS_FAILURE,
  LOAD_LOGS_REQUEST,
  LOAD_LOGS_SUCCESS
};
