export const DISMISS_ALERT = 'DISMISS_ALERT';
export const FETCH_API_COMPLETE = 'FETCH_API_COMPLETE';
export const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';
export const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
