const DISMISS_ALERT = 'DISMISS_ALERT';
const FETCH_API_COMPLETE = 'FETCH_API_COMPLETE';
const FETCH_API_REQUEST = 'FETCH_API_REQUEST';
const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';
const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST';
const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';

export {
  DISMISS_ALERT,
  FETCH_API_COMPLETE,
  FETCH_API_REQUEST,
  LOAD_EVENTS_FAILURE,
  LOAD_EVENTS_REQUEST,
  LOAD_EVENTS_SUCCESS
};
